version: "3"
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    container_name: db-laravel
    image: mysql:8.0
    env_file:
      - .env_file
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest

    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
